In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/ncaa-tourney-training-data/MVConfData.csv
/kaggle/input/ncaa-tourney-training-data/TourneyPredictorTrainingData.csv
/kaggle/input/ncaa-tourney-training-data/MAAConfData.csv
/kaggle/input/ncaa-tourney-training-data/TourneyFullData.csv
/kaggle/input/ncaa-tourney-training-data/WAConfData.csv
/kaggle/input/ncaa-tourney-training-data/SLandConfData.csv
/kaggle/input/ncaa-tourney-training-data/ACConfData.csv
/kaggle/input/ncaa-tourney-training-data/test2015.csv
/kaggle/input/ncaa-tourney-training-data/B12ConfData.csv
/kaggle/input/ncaa-tourney-training-data/MAConfData.csv
/kaggle/input/ncaa-tourney-training-data/Test2016.csv
/kaggle/input/ncaa-tourney-training-data/BEastConfData.csv
/kaggle/input/ncaa-tourney-training-data/Fieldof682023.csv
/kaggle/input/ncaa-tourney-training-data/OVConfData.csv
/kaggle/input/ncaa-tourney-training-data/SEConfData.csv
/kaggle/input/ncaa-tourney-training-data/IVYConfData.csv
/kaggle/input/ncaa-tourney-training-data/NEConfData.csv
/kaggle/input/nca

In [2]:
import statistics
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn import neighbors

In [3]:
df = pd.read_csv('../input/ncaa-tourney-training-data/TourneyFullData.csv')
df

Team    ADJOE    ADJDE  BARTHAG   W   G   EFG  EFGd   FTR  FTRD  \
0        Indiana  107.973   90.507   0.8838  20  33  51.3  45.6  33.5  30.6   
1     Wright St.  104.209  106.863   0.4282  20  33  52.0  51.2  31.1  26.0   
2            UAB  111.104   98.065   0.8078  25  32  52.9  47.9  29.5  31.5   
3      Villanova  117.142   92.968   0.9345  26  33  52.0  47.5  30.5  25.1   
4        Arizona  118.039   92.430   0.9433  31  34  55.9  44.4  35.1  22.8   
..           ...      ...      ...      ...  ..  ..   ...   ...   ...   ...   
471    Manhattan  100.497   99.602   0.5257  19  32  49.7  48.0  47.9  51.9   
472    Lafayette  112.100  116.200   0.3979  19  32  55.8  53.5  30.4  27.5   
473         Utah  115.121   88.865   0.9515  23  31  55.6  42.7  42.8  34.5   
474  Wichita St.  114.096   91.693   0.9251  27  31  50.7  45.2  35.4  36.8   
475    Boise St.  109.506   97.090   0.7996  23  31  53.5  47.4  32.9  31.5   

     ...  2Pper  2PperD  3Pper  3PperD  ADJTEMP    Yr     WAB  BestPlyr  \
0    ...   51.4    43.4   33.9    32.6     68.2  2022  0.2242       5.2   
1    ...   53.2    51.6   33.0    33.7     69.6  2022 -8.3947       4.3   
2    ...   50.6    47.5   38.3    32.4     69.9  2022 -0.1033       4.7   
3    ...   50.3    48.2   35.9    31.0     63.6  2022  7.2884       5.7   
4    ...   57.5    41.9   35.4    32.7     73.4  2022  8.7612       4.6   
..   ...    ...     ...    ...     ...      ...   ...     ...       ...   
471  ...   48.9    47.9   34.0    32.2     67.9  2015 -7.3694       2.6   
472  ...   52.8    51.5   40.8    38.0     64.5  2015 -6.8000       3.9   
473  ...   52.8    40.9   40.2    31.6     61.5  2015  3.6546       5.8   
474  ...   48.9    42.5   35.9    34.4     62.2  2015  4.4218       4.9   
475  ...   49.8    47.8   39.1    31.2     63.7  2015  0.4686       4.8   

     SigWARPlyr  AdvScore  
0             3         0  
1             3         0  
2             4         0  
3             6        15  
4             6         3  
..          ...       ...  
471           3        -1  
472           4         0  
473           4         3  
474           4         3  
475           5        -1  

[476 rows x 24 columns]

In [4]:
df = df.drop(columns = ['Team', 'Yr']);
df

ADJOE    ADJDE  BARTHAG   W   G   EFG  EFGd   FTR  FTRD   TOR  ...  \
0    107.973   90.507   0.8838  20  33  51.3  45.6  33.5  30.6  17.3  ...   
1    104.209  106.863   0.4282  20  33  52.0  51.2  31.1  26.0  17.9  ...   
2    111.104   98.065   0.8078  25  32  52.9  47.9  29.5  31.5  16.3  ...   
3    117.142   92.968   0.9345  26  33  52.0  47.5  30.5  25.1  15.5  ...   
4    118.039   92.430   0.9433  31  34  55.9  44.4  35.1  22.8  18.0  ...   
..       ...      ...      ...  ..  ..   ...   ...   ...   ...   ...  ...   
471  100.497   99.602   0.5257  19  32  49.7  48.0  47.9  51.9  21.0  ...   
472  112.100  116.200   0.3979  19  32  55.8  53.5  30.4  27.5  17.1  ...   
473  115.121   88.865   0.9515  23  31  55.6  42.7  42.8  34.5  17.8  ...   
474  114.096   91.693   0.9251  27  31  50.7  45.2  35.4  36.8  15.2  ...   
475  109.506   97.090   0.7996  23  31  53.5  47.4  32.9  31.5  16.1  ...   

      DRB  2Pper  2PperD  3Pper  3PperD  ADJTEMP     WAB  BestPlyr  \
0    25.0   51.4    43.4   33.9    32.6     68.2  0.2242       5.2   
1    30.0   53.2    51.6   33.0    33.7     69.6 -8.3947       4.3   
2    27.4   50.6    47.5   38.3    32.4     69.9 -0.1033       4.7   
3    28.0   50.3    48.2   35.9    31.0     63.6  7.2884       5.7   
4    28.3   57.5    41.9   35.4    32.7     73.4  8.7612       4.6   
..    ...    ...     ...    ...     ...      ...     ...       ...   
471  33.7   48.9    47.9   34.0    32.2     67.9 -7.3694       2.6   
472  34.5   52.8    51.5   40.8    38.0     64.5 -6.8000       3.9   
473  28.1   52.8    40.9   40.2    31.6     61.5  3.6546       5.8   
474  27.0   48.9    42.5   35.9    34.4     62.2  4.4218       4.9   
475  25.9   49.8    47.8   39.1    31.2     63.7  0.4686       4.8   

     SigWARPlyr  AdvScore  
0             3         0  
1             3         0  
2             4         0  
3             6        15  
4             6         3  
..          ...       ...  
471           3        -1  
472           4         0  
473           4         3  
474           4         3  
475           5        -1  

[476 rows x 22 columns]

In [5]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1]

In [6]:
bay = linear_model.BayesianRidge()
bay.fit(x,y)
bay.coef_

array([ 0.24409246, -0.08609972, -0.01529612,  0.14374282, -0.04466585,
        0.08174654, -0.02709814, -0.05396614, -0.06774149, -0.01564194,
        0.13919609,  0.09993405,  0.07083755,  0.10899859,  0.01907866,
       -0.00522774, -0.04814577, -0.02448515,  0.17581359,  0.02463878,
       -0.02656524])

In [7]:
lars = linear_model.LassoLars(alpha=0.0001)
lars.fit(x,y)
lars.coef_

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_base.py:138: FutureWarning: The default of 'normalize' will be set to False in version 1.2 and deprecated in version 1.4.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LassoLars())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * np.sqrt(n_samples). 
  FutureWarning,


array([ 1.52324769e+00, -1.62859546e+00, -6.62173050e+01,  4.54022839e-01,
       -3.38823088e-01,  6.96379278e-01, -9.20739683e-01, -1.19719226e-01,
       -5.43491303e-03,  2.54235990e-01, -8.69504390e-02, -5.51850987e-02,
        1.95317514e-01, -4.32495063e-01,  9.90591929e-01, -5.39148517e-01,
        7.60736659e-01, -7.01518563e-02, -1.82447003e-03, -4.59289191e-02,
       -4.35688661e-01])

In [8]:
n_neighbors = 20

for i, weights in enumerate(["uniform", "distance"]):
    knn = neighbors.KNeighborsRegressor(n_neighbors, weights=weights)
knn.fit(x,y)

KNeighborsRegressor(n_neighbors=20, weights='distance')

In [9]:
reg = linear_model.LinearRegression()
reg.fit(x,y)
reg.coef_

array([ 1.54952547e+00, -1.65968666e+00, -6.65945171e+01,  4.93672708e-01,
       -3.64498255e-01,  9.58739728e-01, -1.22656631e+00, -1.22793757e-01,
       -3.80700776e-03,  2.80051223e-01, -1.08482450e-01, -6.36972444e-02,
        2.05092842e-01, -6.15963487e-01,  1.20585034e+00, -6.99417578e-01,
        9.43162474e-01, -6.91995736e-02, -4.05364563e-02, -5.88355926e-02,
       -4.42661156e-01])

In [10]:
tourney = pd.read_csv('../input/ncaa-tourney-training-data/Fieldof682023.csv')
tourneyTeams = tourney.iloc[:,0]
tourneyTeams

0           UC Santa Barbara
1                    Indiana
2         North Carolina St.
3                     Furman
4                     Xavier
               ...          
63    Southeast Missouri St.
64                   Colgate
65                       USC
66                 Princeton
67                 Boise St.
Name: Team, Length: 68, dtype: object

In [11]:
tourney = tourney.drop(columns = ['Team', 'Yr']);

In [12]:
tourneyBay = bay.predict(tourney)
tourneyLars = lars.predict(tourney)
tourneyKnn = knn.predict(tourney)
tourneyReg = reg.predict(tourney)
tabletourney = pd.DataFrame({'teams':tourneyTeams, 'Bay':tourneyBay, 'Lars':tourneyLars, 'KNN':tourneyKnn, 'Linear':tourneyReg})
pd.set_option('display.max_rows', None)
tabletourney.sort_values("Bay")

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:444: UserWarning: X has feature names, but BayesianRidge was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
/opt/conda/lib/python3.7/site-packages/sklearn/base.py:444: UserWarning: X has feature names, but LassoLars was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
/opt/conda/lib/python3.7/site-packages/sklearn/base.py:444: UserWarning: X has feature names, but KNeighborsRegressor was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
/opt/conda/lib/python3.7/site-packages/sklearn/base.py:444: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


teams       Bay       Lars        KNN     Linear
33          Texas Southern -7.397529   0.790172  -0.227457   0.971719
63  Southeast Missouri St. -6.102332   0.597324  -0.325895   0.640704
25     Fairleigh Dickinson -3.331282   0.455330  -0.156461   0.404632
6                   Howard -1.704507   2.748122  -0.092500   2.834001
44  Texas A&M Corpus Chris -1.553682   1.547844   0.292293   1.600051
28             Montana St. -0.826857  -1.115724   0.051525  -0.960892
31       Northern Kentucky -0.714500   2.808893   0.058897   2.896286
62           UNC Asheville -0.484553   1.251077  -0.185017   1.193351
66               Princeton -0.139565  -0.970636   0.193259  -0.941084
49            Kennesaw St. -0.127515   0.158979  -0.087356   0.161584
39            Grand Canyon  0.305656  -2.419552   0.065374  -2.377290
51                 Vermont  0.452964  -1.327611   0.520797  -1.349121
21                  Nevada  0.762001  -1.700913   0.286614  -1.702661
47             Arizona St.  1.124358  -2.276123   0.718813  -2.414712
29            Northwestern  1.658819   0.589778   0.572628   0.535074
0         UC Santa Barbara  1.902707   1.335270   0.045917   1.395130
54         Mississippi St.  1.992609   0.007238   1.009314   0.043536
46     Louisiana Lafayette  2.050186   0.347320   0.986174   0.423889
40            Michigan St.  2.122730   0.314793   1.220634   0.191198
59              Pittsburgh  2.312744  -1.755075   0.506230  -1.844614
23                Illinois  2.470762  -1.572025   1.488563  -1.726802
53                   Drake  2.481080   0.504602   2.419643   0.586706
61                Arkansas  2.581883   1.514726   1.449905   1.624593
67               Boise St.  2.643863   0.155121   0.606819   0.125511
60                     VCU  2.651641  -0.184647   0.709807  -0.159136
64                 Colgate  2.748808  -0.409800   1.077792  -0.492768
13                Kent St.  2.775463   1.045511   0.912429   1.075499
10                Penn St.  2.963998   1.203517   0.986475   1.255081
34                  Auburn  3.019988   1.966432   0.868982   1.983364
65                     USC  3.050766  -0.502229   1.220774  -0.562086
8                 Maryland  3.075740   0.673492   0.905384   0.630593
50                Iowa St.  3.134721   2.825905   2.046627   2.715419
35                Virginia  3.167264   0.534655   2.976242   0.412477
3                   Furman  3.198754   0.462142   0.094406   0.265799
15              Providence  3.206919  -0.865087   2.421887  -0.929284
2       North Carolina St.  3.305283  -0.210445   0.752768  -0.287336
48                    Iona  3.339315  -0.950517   0.458634  -0.989071
26           West Virginia  3.381344   2.948677   1.019358   2.957959
1                  Indiana  3.448140   0.110607   0.595251  -0.125503
17               Creighton  3.686407   3.420375   2.886937   3.513841
32              Kansas St.  3.707636   3.199411   1.966176   3.191054
42                     TCU  4.010098   1.903643   1.906895   1.976783
41                    Iowa  4.141042   1.261438   1.481084   1.244143
36                Kentucky  4.146506   1.315628   1.487845   1.195095
7                 Utah St.  4.241496   2.532505   1.071096   2.585434
20               Texas A&M  4.304292   3.602410   2.027460   3.588502
30   College of Charleston  4.410274   0.574311   1.236287   0.552657
43            Saint Mary's  4.676161   5.857348   4.131555   5.958551
12            Oral Roberts  4.695079   1.122809   0.999909   0.978289
18                    Duke  5.042021   2.662742   2.546641   2.711508
27           San Diego St.  5.138433   8.502688   2.242288   8.682274
22               Tennessee  5.236256   5.565659   4.774820   5.575914
5         Florida Atlantic  5.344692   2.646930   3.797189   2.715600
16                 Memphis  5.623595   5.973771   2.386334   5.999029
4                   Xavier  5.650441   3.915340   1.468443   3.834982
57                Missouri  6.033695   4.077559   2.204181   3.905638
45                Miami FL  6.0