In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/ncaa-tourney-training-data/MVConfData.csv
/kaggle/input/ncaa-tourney-training-data/TourneyPredictorTrainingData.csv
/kaggle/input/ncaa-tourney-training-data/MAAConfData.csv
/kaggle/input/ncaa-tourney-training-data/TourneyFullData.csv
/kaggle/input/ncaa-tourney-training-data/WAConfData.csv
/kaggle/input/ncaa-tourney-training-data/SLandConfData.csv
/kaggle/input/ncaa-tourney-training-data/ACConfData.csv
/kaggle/input/ncaa-tourney-training-data/test2015.csv
/kaggle/input/ncaa-tourney-training-data/B12ConfData.csv
/kaggle/input/ncaa-tourney-training-data/MAConfData.csv
/kaggle/input/ncaa-tourney-training-data/Test2016.csv
/kaggle/input/ncaa-tourney-training-data/BEastConfData.csv
/kaggle/input/ncaa-tourney-training-data/Fieldof682023.csv
/kaggle/input/ncaa-tourney-training-data/OVConfData.csv
/kaggle/input/ncaa-tourney-training-data/SEConfData.csv
/kaggle/input/ncaa-tourney-training-data/IVYConfData.csv
/kaggle/input/ncaa-tourney-training-data/NEConfData.csv
/kaggle/input/nca

In [2]:
# import all of the python modules/packages you'll need here
import matplotlib.pyplot as plt
import statistics
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn import linear_model
# ...

In [3]:
df = pd.read_csv('../input/ncaa-tourney-training-data/TourneyPredictorTrainingData.csv')
df

Team    ADJOE    ADJDE  BARTHAG   W   G   EFG  EFGd  \
0                   Indiana  107.973   90.507   0.8838  20  33  51.3  45.6   
1                Wright St.  104.209  106.863   0.4282  20  33  52.0  51.2   
2                       UAB  111.104   98.065   0.8078  25  32  52.9  47.9   
3                 Villanova  117.142   92.968   0.9345  26  33  52.0  47.5   
4                   Arizona  118.039   92.430   0.9433  31  34  55.9  44.4   
..                      ...      ...      ...      ...  ..  ..   ...   ...   
335  North Carolina Central  101.818  100.759   0.5300  22  30  51.8  45.1   
336                Arkansas  115.356  101.139   0.8194  25  34  51.5  48.2   
337                  Dayton  110.492   96.542   0.8252  23  30  54.2  47.7   
338                     USC  111.201   99.606   0.7801  24  33  51.9  49.7   
339             Wichita St.  116.905   92.842   0.9340  29  33  54.7  43.9   

      FTR  FTRD  ...  2Pper  2PperD  3Pper  3PperD  ADJTEMP    Yr     WAB  \
0    33.5  30.6  ...   51.4    43.4   33.9    32.6     68.2  2022  0.2242   
1    31.1  26.0  ...   53.2    51.6   33.0    33.7     69.6  2022 -8.3947   
2    29.5  31.5  ...   50.6    47.5   38.3    32.4     69.9  2022 -0.1033   
3    30.5  25.1  ...   50.3    48.2   35.9    31.0     63.6  2022  7.2884   
4    35.1  22.8  ...   57.5    41.9   35.4    32.7     73.4  2022  8.7612   
..    ...   ...  ...    ...     ...    ...     ...      ...   ...     ...   
335  34.8  27.6  ...   53.0    45.9   33.3    29.1     67.9  2017 -4.9820   
336  38.8  39.3  ...   50.2    47.2   36.4    33.2     70.9  2017  3.8886   
337  43.7  34.6  ...   51.8    47.2   38.7    32.4     69.8  2017  1.5564   
338  37.2  23.9  ...   50.5    46.8   36.3    36.5     70.5  2017  1.3601   
339  40.9  35.2  ...   51.0    42.3   40.7    31.0     70.5  2017  4.1891   

     BestPlyr  SigWARPlyr  AdvScore  
0         5.2           3         0  
1         4.3           3         0  
2         4.7           4         0  
3         5.7           6        15  
4         4.6           6         3  
..        ...         ...       ...  
335       2.9           2        -1  
336       3.7           5         1  
337       3.6           5         0  
338       4.0           4         1  
339       3.9           5         1  

[340 rows x 24 columns]

In [4]:
df = df.drop(columns = ['Team', 'Yr']);
df

ADJOE    ADJDE  BARTHAG   W   G   EFG  EFGd   FTR  FTRD   TOR  ...  \
0    107.973   90.507   0.8838  20  33  51.3  45.6  33.5  30.6  17.3  ...   
1    104.209  106.863   0.4282  20  33  52.0  51.2  31.1  26.0  17.9  ...   
2    111.104   98.065   0.8078  25  32  52.9  47.9  29.5  31.5  16.3  ...   
3    117.142   92.968   0.9345  26  33  52.0  47.5  30.5  25.1  15.5  ...   
4    118.039   92.430   0.9433  31  34  55.9  44.4  35.1  22.8  18.0  ...   
..       ...      ...      ...  ..  ..   ...   ...   ...   ...   ...  ...   
335  101.818  100.759   0.5300  22  30  51.8  45.1  34.8  27.6  17.9  ...   
336  115.356  101.139   0.8194  25  34  51.5  48.2  38.8  39.3  16.4  ...   
337  110.492   96.542   0.8252  23  30  54.2  47.7  43.7  34.6  17.1  ...   
338  111.201   99.606   0.7801  24  33  51.9  49.7  37.2  23.9  15.7  ...   
339  116.905   92.842   0.9340  29  33  54.7  43.9  40.9  35.2  15.9  ...   

      DRB  2Pper  2PperD  3Pper  3PperD  ADJTEMP     WAB  BestPlyr  \
0    25.0   51.4    43.4   33.9    32.6     68.2  0.2242       5.2   
1    30.0   53.2    51.6   33.0    33.7     69.6 -8.3947       4.3   
2    27.4   50.6    47.5   38.3    32.4     69.9 -0.1033       4.7   
3    28.0   50.3    48.2   35.9    31.0     63.6  7.2884       5.7   
4    28.3   57.5    41.9   35.4    32.7     73.4  8.7612       4.6   
..    ...    ...     ...    ...     ...      ...     ...       ...   
335  31.4   53.0    45.9   33.3    29.1     67.9 -4.9820       2.9   
336  33.5   50.2    47.2   36.4    33.2     70.9  3.8886       3.7   
337  27.0   51.8    47.2   38.7    32.4     69.8  1.5564       3.6   
338  31.2   50.5    46.8   36.3    36.5     70.5  1.3601       4.0   
339  24.2   51.0    42.3   40.7    31.0     70.5  4.1891       3.9   

     SigWARPlyr  AdvScore  
0             3         0  
1             3         0  
2             4         0  
3             6        15  
4             6         3  
..          ...       ...  
335           2        -1  
336           5         1  
337           5         0  
338           4         1  
339           5         1  

[340 rows x 22 columns]

In [5]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1]
X_train_raw, X_val_raw, y_train, y_val = train_test_split(x, y, test_size=0.15, random_state=68)
X_train_raw

array([[108.72  ,  90.173 ,   0.8958, ...,   4.3806,   3.6   ,   5.    ],
       [118.031 ,  94.261 ,   0.93  , ...,   5.0072,   5.    ,   5.    ],
       [101.705 , 106.649 ,   0.3668, ...,  -4.3099,   4.8   ,   3.    ],
       ...,
       [119.419 ,  93.721 ,   0.9419, ...,   7.9687,   5.    ,   6.    ],
       [112.07  ,  86.316 ,   0.9527, ...,   7.0081,   4.7   ,   4.    ],
       [108.074 ,  96.591 ,   0.7844, ...,  -0.2937,   3.1   ,   4.    ]])

# Bayesian Ridge Training

In [6]:
bay = linear_model.BayesianRidge()
bay.fit(X_train_raw,y_train)
bay.coef_

array([ 0.24303159, -0.07579713, -0.00752367,  0.08499398, -0.06024288,
        0.08432243, -0.02520844, -0.07418874, -0.01157645,  0.02257836,
        0.11587147,  0.14777475,  0.04269692,  0.04877668,  0.04242722,
        0.08139785, -0.082818  ,  0.00222181,  0.17185129,  0.05446593,
       -0.01325338])

In [7]:
bayPreds = bay.predict(X_val_raw)
table = pd.DataFrame({'Actual':y_val, 'Predictions': bayPreds, 'Difference':(y_val - bayPreds)})
print(table)
print("Mean Squared Error: " + str(mean_squared_error(y_val, bayPreds)))

     Actual  Predictions  Difference
81        3     4.097288   -1.097288
330       0    -3.729036    3.729036
177       0     3.342990   -3.342990
144       1     3.096773   -2.096773
223      31     4.507435   26.492565
129       7     3.679152    3.320848
326       1     5.444441   -4.444441
16       15     7.437913    7.562087
155       0     2.940445   -2.940445
262       0     1.093578   -1.093578
325       0     1.938010   -1.938010
65        0     2.689646   -2.689646
241       0     5.348904   -5.348904
273      -1     3.818243   -4.818243
277       0    -3.748316    3.748316
159       0     0.455489   -0.455489
107      -1    -0.091344   -0.908656
115       0     2.830566   -2.830566
224       0    -0.754455    0.754455
3        15     6.066354    8.933646
30        1     5.266721   -4.266721
165       0     3.090548   -3.090548
268       0     3.831008   -3.831008
252       0    -1.753085    1.753085
79        0     3.113133   -3.113133
334       0     2.789544   -2.789544
2

# Lasso Lars Training

In [8]:
lars = linear_model.LassoLars(alpha=0.0001)
lars.fit(X_train_raw,y_train)
lars.coef_

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_base.py:138: FutureWarning: The default of 'normalize' will be set to False in version 1.2 and deprecated in version 1.4.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LassoLars())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * np.sqrt(n_samples). 
  FutureWarning,


array([ 1.38497488e+00, -1.44919092e+00, -6.51639603e+01,  2.27832858e-01,
       -1.87829930e-01, -6.46566680e-02, -1.98360717e+00, -1.39741567e-01,
        4.48850019e-02,  4.33890618e-01,  1.56671370e-01, -1.25786409e-02,
       -8.71048685e-03, -6.04168921e-02,  1.68370876e+00,  2.26489515e-01,
        1.12854244e+00,  4.85262990e-02,  2.17731617e-01,  4.92308489e-01,
       -3.73568415e-01])

In [9]:
larsPreds = lars.predict(X_val_raw)
table1 = pd.DataFrame({'Actual':y_val, 'Predictions': larsPreds, 'Difference':(y_val - larsPreds)})
print(table1)
print("Mean Squared Error: " + str(mean_squared_error(y_val, larsPreds)))

     Actual  Predictions  Difference
81        3     2.375430    0.624570
330       0     2.403805   -2.403805
177       0     1.676292   -1.676292
144       1    -0.512365    1.512365
223      31     5.479983   25.520017
129       7     3.460425    3.539575
326       1     3.115497   -2.115497
16       15     8.589748    6.410252
155       0     1.846972   -1.846972
262       0    -1.142435    1.142435
325       0     0.276656   -0.276656
65        0    -2.011062    2.011062
241       0     4.269330   -4.269330
273      -1     3.869751   -4.869751
277       0     1.696278   -1.696278
159       0    -1.370393    1.370393
107      -1    -1.639239    0.639239
115       0     0.110219   -0.110219
224       0    -0.689953    0.689953
3        15     8.393257    6.606743
30        1     5.743465   -4.743465
165       0     5.080203   -5.080203
268       0     1.630324   -1.630324
252       0     2.948497   -2.948497
79        0     3.630385   -3.630385
334       0     0.455165   -0.455165
2

# K Nearest Neighbors Training

In [10]:
from sklearn import neighbors
n_neighbors = 20

for i, weights in enumerate(["uniform", "distance"]):
    knn = neighbors.KNeighborsRegressor(n_neighbors, weights=weights)
knn = knn.fit(X_train_raw,y_train)

In [11]:
nnPreds = knn.predict(X_val_raw)
table2 = pd.DataFrame({'Actual':y_val, 'Predictions': nnPreds, 'Difference':(y_val - nnPreds)})
print(table2)
print("Mean Squared Error: " + str(mean_squared_error(y_val, nnPreds)))

     Actual  Predictions  Difference
81        3     1.124987    1.875013
330       0    -0.047125    0.047125
177       0     1.586790   -1.586790
144       1     1.100781   -0.100781
223      31     0.959419   30.040581
129       7     0.783846    6.216154
326       1     2.387642   -1.387642
16       15     9.231457    5.768543
155       0     1.135148   -1.135148
262       0     0.615151   -0.615151
325       0     0.104585   -0.104585
65        0     1.492852   -1.492852
241       0     1.448428   -1.448428
273      -1     1.164070   -2.164070
277       0     0.174177   -0.174177
159       0     1.030294   -1.030294
107      -1     0.730288   -1.730288
115       0     1.012159   -1.012159
224       0    -0.046566    0.046566
3        15     4.674670   10.325330
30        1     4.091941   -3.091941
165       0     1.008444   -1.008444
268       0     1.683996   -1.683996
252       0     0.002878   -0.002878
79        0     2.195096   -2.195096
334       0     0.252794   -0.252794
2

# Linear Regression

In [12]:
reg = linear_model.LinearRegression()
reg.fit(X_train_raw,y_train)
reg.coef_

array([ 1.41249372e+00, -1.45982699e+00, -6.56105783e+01,  2.47317564e-01,
       -2.00758904e-01, -2.11354969e-01, -2.33875355e+00, -1.42577213e-01,
        4.54982978e-02,  4.64917649e-01,  1.59597474e-01, -2.73125692e-02,
       -1.46158821e-02,  1.07165324e-02,  1.91021396e+00,  2.93834278e-01,
        1.32935924e+00,  5.19679273e-02,  1.99441801e-01,  4.97048940e-01,
       -3.81098520e-01])

In [13]:
regPreds = reg.predict(X_val_raw)
table3 = pd.DataFrame({'Actual':y_val, 'Predictions': regPreds, 'Difference':(y_val - regPreds)})
print(table3)
print("Mean Squared Error: " + str(mean_squared_error(y_val, regPreds)))

     Actual  Predictions  Difference
81        3     2.333611    0.666389
330       0     2.550552   -2.550552
177       0     1.670456   -1.670456
144       1    -0.571815    1.571815
223      31     5.523801   25.476199
129       7     3.479363    3.520637
326       1     3.059234   -2.059234
16       15     8.542526    6.457474
155       0     1.921374   -1.921374
262       0    -1.048852    1.048852
325       0     0.165743   -0.165743
65        0    -1.989871    1.989871
241       0     4.277160   -4.277160
273      -1     3.930063   -4.930063
277       0     1.844289   -1.844289
159       0    -1.341947    1.341947
107      -1    -1.654826    0.654826
115       0     0.003835   -0.003835
224       0    -0.696042    0.696042
3        15     8.388480    6.611520
30        1     5.799944   -4.799944
165       0     5.137885   -5.137885
268       0     1.546560   -1.546560
252       0     3.066807   -3.066807
79        0     3.687437   -3.687437
334       0     0.421776   -0.421776
2